# Generated by Django 4.0 on 2022-10-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='48*48 크기의 png/jpeg파일을 업로드해주세요', upload_to='accounts/profile/%Y/%m'),
        ),
    ]
