# Generated by Django 4.0 on 2022-11-07 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^010-?\\d{3}-?\\d{4}$')]),
        ),
    ]
