# Generated by Django 4.0 on 2022-11-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
