# Generated by Django 4.0 on 2022-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0002_playlist_desc_alter_playlist_title_alter_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='playlists/cover_images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='song',
            name='album_cover',
            field=models.ImageField(blank=True, upload_to='album_covers/%Y/%m'),
        ),
    ]
